name: 'Run smoke tests'
description: 'Runs smoke tests'
inputs:
  python-version:
    required: true
    description: >-
      Python version to use. Must be in the form of "3.xx".
runs:
  using: "composite"
  steps:
    - name: "Install packages"
      shell: bash
      run: |
        cat /etc/os-release
        sudo dnf install -y gcc gcc-c++ make git-core python${{ inputs.python-version }} python${{ inputs.python-version }}-devel

    - name: "Verify cuda environment is setup"
      shell: bash
      run: |
        export CUDA_HOME="/usr/local/cuda"
        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CUDA_HOME}/lib64:${CUDA_HOME}/extras/CUPTI/lib64"
        export PATH="${PATH}:${CUDA_HOME}/bin"
        nvidia-smi

    - name: "Install uv"
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    # installs in $GITHUB_WORKSPACE/venv.
    # only has to install Tox because Tox will do the other virtual environment management.
    - name: "Setup Python virtual environment"
      shell: bash
      run: |
        uv venv venv --python python${{ inputs.python-version }}
        . venv/bin/activate
        uv pip install tox tox-uv -c constraints-dev.txt

    # flash-attn has a bug in the setup.py that causes pip to attempt
    # installing it before torch is installed. This is a bug because their
    # setup.py depends on importing the module, so it should have been listed
    # in build_requires. Alas. See:
    # https://github.com/Dao-AILab/flash-attention/pull/958
    - name: "Install torch and other unlisted build dependencies for flash-attn"
      shell: bash
      run: |
        source venv/bin/activate
        # The list is taken from the pull request linked above
        uv pip install torch packaging setuptools wheel psutil ninja -c constraints-dev.txt

    - name: "Install dependencies from tox.ini in the current venv"
      shell: bash
      run: |
        source venv/bin/activate
        tox -e py3-smoke --print-deps-to-file=./deps.txt
        uv pip install -c constraints-dev.txt -r ./deps.txt --no-build-isolation
        uv pip install -c constraints-dev.txt .

    - name: "Show disk utilization BEFORE tests"
      shell: bash
      if: always()
      run: |
        df -h

    - name: "Run smoke tests with Tox and Pytest"
      shell: bash
      run: |
        source venv/bin/activate
        tox -e py3-smoke

    - name: "Show disk utilization AFTER tests"
      shell: bash
      if: always()
      run: |
        df -h
