# Aligned with: https://github.com/instructlab/dev-docs/pull/198
name: Update constraints-dev.txt

on:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  update-constraints:
    if: github.repository_owner == 'instructlab'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Checkout "update-constraints" in-house CI action
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: instructlab/ci-actions
          path: ci-actions
          # no tag that includes https://github.com/instructlab/ci-actions/pull/26, yet
          ref: 88641ccaf122964eacdc1a82b18bda369b6f99bd # main
          sparse-checkout: |
            actions/update-constraints

      - name: Update constraints
        id: update-constraints
        uses: ./ci-actions/actions/update-constraints
        with:
          gh-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

