# SPDX-License-Identifier: Apache-2.0

name: Lint, Format, and MyPy

on:
  push:
    branches:
      - "main"
      - "release-**"
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'tox.ini'
      - '.pylintrc'
      - 'scripts/*.sh' # Used by this workflow
      - '.github/workflows/lint.yml' # This workflow
  pull_request:
    branches:
      - "main"
      - "release-**"
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'tox.ini'
      - '.pylintrc'
      - 'scripts/*.sh' # Used by this workflow
      - '.github/workflows/lint.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "${{ matrix.lint.name }}"
    strategy:
      fail-fast: false
      matrix:
        lint:
          - name: "ruff"
            commands: |
              tox -e ruff -- check
          - name: "pylint"
            commands: |
              echo "::add-matcher::.github/workflows/matchers/pylint.json"
              tox -e lint
          - name: "mypy"
            commands: |
              tox -e mypy
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # https://github.com/actions/checkout/issues/249
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/requirements*.txt

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh

      - name: "${{ matrix.lint.name }}"
        run: |
          ${{ matrix.lint.commands }}
        env:
          RUFF_OUTPUT_FORMAT: github

  lint-workflow-complete:
    needs: ["lint"]
    runs-on: ubuntu-latest
    steps:
      - name: Lint Workflow Complete
        run: echo "Lint Workflow Complete"
